services:
  sql:
    container_name: sqlserver
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password@123    
    
  products:
    container_name: app-products
    image: ${DOCKER_REGISTRY-}products
    build:
      context: .
      dockerfile: Products/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - sql
    environment:
      - ASPNETCORE_URLS=http://+:5001
    restart: always

#   redis:
#      image: redis:latest
#      restart: always
#      ports:
#         - "6379:6379"
#      volumes:
#         - redis-data:/data

# volumes:
#   redis-data:
